### ISSUE TITLE
No connectivity between EC2 and S3

### ISSUE THREAD

**Issue by amakhnev** [matt-bartel/vaultwarden-tf-aws#1]
I forked the repo to adjust the scripts and use without Route 53, and came across the issue when EC2 didn't have the access to S3. This was because of missing route table association between route table and  endpoint, it's necessary to adust the network,tf and add follow code:
```
resource "aws_vpc_endpoint_route_table_association" "route_table_association" {
  route_table_id = aws_default_route_table.r.id
  vpc_endpoint_id = aws_vpc_endpoint.s3.id
}
``` 
I am not doing PR as have already removed Route 53 bits from there! Good luck and many thanks!

**Comment by matt-bartel** [comment]
Thanks! Not sure how I missed that.
